spring.application.name=chatflow-backend
spring.data.mongodb.uri=mongodb+srv://Admin:fathima1011@codes.j12ieo6.mongodb.net/chatflow?retryWrites=true&w=majority&appName=Codes
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
spring.main.banner-mode=off
spring.main.log-startup-info=false
spring.main.lazy-initialization=true
spring.data.mongodb.auto-index-creation=true
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.mongodb.driver=ERROR
app.crypto.secret=${CHATFLOW_CRYPTO_SECRET:chatflow-dev-secret-change-me-please}
