spring.application.name=chatflow-backend
spring.data.mongodb.uri=mongodb+srv://Admin:fathima1011@codes.j12ieo6.mongodb.net/chatflow?retryWrites=true&w=majority&appName=Codes
spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB